name: Test under Windows
on: push
jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        include:
          - python-version: '3.6'
            toxenv: "py36-doctest"

          - python-version: '3.6'
            toxenv: "py36-test"

          - python-version: '3.7'
            toxenv: "py37-doctest"

          - python-version: '3.7'
            toxenv: "py37-test"

          - python-version: '3.8'
            toxenv: "py38-doctest"

          - python-version: '3.8'
            toxenv: "py38-test"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip
        run: pip install -U pip

      - name: Install tox
        run: pip install tox

      - name: Test using Tox
        run: tox -vv
