name: Release to PyPI

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  tarball:
    if: github.event_name == 'push'
    timeout-minutes: 1
    runs-on: ubuntu-20.04
    env:
      PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v1
        with:
          python-version: "3.8.x"

      # https://github.community/t/how-to-get-just-the-tag-name/16241/4
      - name: Extract the version number
        id: get_version
        run: |
          echo ::set-output name=V::$(python smart_open/version.py)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          . venv/bin/activate
          pip install twine

      - name: Build tarball
        run: |
          . venv/bin/activate
          python setup.py sdist bdist_wheel

      - name: Upload tarball to PyPI
        run: |
          . venv/bin/activate
          twine upload dist/smart_open-${{ steps.get_version.outputs.V }}.tar.gz -u ${{ env.PYPI_USERNAME }} -p ${{ env.PYPI_PASSWORD }}
